name: check-release.yaml
on:
  push:
    branches:
      - master

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  SEMVER_PATTERN: ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-rc\.([0-9]+))?$
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check whether version matches semver pattern
        run: "VERSION=$(cat VERSION)\nif [[ ${VERSION} =~ ${{ env.SEMVER_PATTERN }}\
          \ ]]; then\n  echo \"Version '${VERSION}' matches semver pattern.\"\nelse\n\
          \  echo \"Version '${VERSION}' does not match semver pattern.\"\n  exit\
          \ 1\nfi\necho \"VERSION=${VERSION}\" >> $GITHUB_ENV\n"
      - id: measurement-3
        name: Record Measurement After Check whether version matches semver pattern
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check whether version matches semver pattern
          task: get-measurement
      - name: Check whether chart version and appVersion matches version
        run: "VERSION=${VERSION#v}\nCHART_VERSION=$(cat charts/spark-operator-chart/Chart.yaml\
          \ | grep version | awk '{print $2}')\nCHART_APP_VERSION=$(cat charts/spark-operator-chart/Chart.yaml\
          \ | grep appVersion | awk '{print $2}')\nif [[ ${CHART_VERSION} == ${VERSION}\
          \ ]]; then\n  echo \"Chart version '${CHART_VERSION}' matches version '${VERSION}'.\"\
          \nelse\n  echo \"Chart version '${CHART_VERSION}' does not match version\
          \ '${VERSION}'.\"\n  exit 1\nfi\nif [[ ${CHART_APP_VERSION} == ${VERSION}\
          \ ]]; then\n  echo \"Chart appVersion '${CHART_APP_VERSION}' matches version\
          \ '${VERSION}'.\"\nelse\n  echo \"Chart appVersion '${CHART_APP_VERSION}'\
          \ does not match version '${VERSION}'.\"\n  exit 1\nfi\n"
      - id: measurement-5
        name: Record Measurement After Check whether chart version and appVersion
          matches version
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check whether chart version and appVersion matches version
          task: get-measurement
      - name: Check if tag exists
        run: "git fetch --tags\nif git tag -l | grep -q \"^${VERSION}$\"; then\n \
          \ echo \"Tag '${VERSION}' already exists.\"\n  exit 1\nelse\n  echo \"Tag\
          \ '${VERSION}' does not exist.\"\nfi\n"
      - id: measurement-7
        name: Record Measurement After Check if tag exists
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check if tag exists
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
