name: stale.yaml
on:
  push:
    branches:
      - master

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/stale@v9
        with:
          close-issue-message: 'This issue has been automatically closed because it
            has not had recent activity. Please comment "/reopen" to reopen it.

            '
          close-pr-message: 'This pull request has been automatically closed because
            it has not had recent activity. Please comment "/reopen" to reopen it.

            '
          days-before-close: 20
          days-before-stale: 90
          exempt-issue-labels: lifecycle/frozen
          exempt-pr-labels: lifecycle/frozen
          operations-per-run: 200
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: lifecycle/stale
          stale-issue-message: 'This issue has been automatically marked as stale
            because it has not had recent activity. It will be closed if no further
            activity occurs. Thank you for your contributions.

            '
          stale-pr-label: lifecycle/stale
          stale-pr-message: 'This pull request has been automatically marked as stale
            because it has not had recent activity. It will be closed if no further
            activity occurs. Thank you for your contributions.

            '
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
